@no-cookie-jar=false

### Create a new portfolio
POST {{host}}/api/portfolios
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{
  "name": "SEBASTIAN CURTIS LAVARIAS",
  "job_title": "FULL STACK WEB DEVELOPER",
  "introduction": "",
  "about": "",
  "email": "sebastiancurtislavarias@gmail.com",
  "phone": "09972217704",
  "website": "https://sebastech.vercel.app/",
  "github": "https://github.com/bastilavarias",
  "linkedin": "",
  "twitter": "",
  "work_experiences": [
    {
      "company": "ChanzIT",
      "role": "Full-stack Web Developer",
      "location": "Philippines",
      "start_date": "2022-10-01",
      "end_date": null,
      "about": ""
    },
    {
      "company": "Vaskeappen",
      "role": "Outsourced Front-end Developer",
      "location": "Drøbak, Norway",
      "start_date": "2021-11-01",
      "end_date": "2022-08-01",
      "about": ""
    },
    {
      "company": "Fourello",
      "role": "Full-stack Web Developer",
      "location": "Philippines",
      "start_date": "2020-12-01",
      "end_date": "2022-10-01",
      "about": ""
    }
  ],
  "education": [
    {
      "school": "Universidad De Manila",
      "level": "Bachelor's Degree",
      "degree": "BS Information Technology",
      "location": "",
      "year_start": null,
      "year_end": 2023,
      "about": ""
    },
    {
      "school": "MMC-CAST",
      "level": "Senior Highschool",
      "degree": null,
      "location": "",
      "year_start": null,
      "year_end": 2018,
      "about": ""
    },
    {
      "school": "Tondo High School",
      "level": "Junior Highschool",
      "degree": null,
      "location": "",
      "year_start": null,
      "year_end": 2016,
      "about": ""
    },
    {
      "school": "Magat Salamat Elementary School",
      "level": "Elementary",
      "degree": null,
      "location": "",
      "year_start": null,
      "year_end": 2012,
      "about": ""
    }
  ],
  "skills": [
    {
      "name": "PHP",
      "url": ""
    },
    {
      "name": "JavaScript",
      "url": ""
    },
    {
      "name": "TypeScript",
      "url": ""
    },
    {
      "name": "Laravel",
      "url": ""
    },
    {
      "name": "Nodejs",
      "url": ""
    },
    {
      "name": "Vue 2",
      "url": ""
    },
    {
      "name": "Vue 3",
      "url": ""
    },
    {
      "name": "React",
      "url": ""
    },
    {
      "name": "Ubuntu / Linux servers",
      "url": ""
    },
    {
      "name": "Digital Ocean",
      "url": ""
    },
    {
      "name": "Docker",
      "url": ""
    },
    {
      "name": "HTML5 + CSS3",
      "url": ""
    },
    {
      "name": "Bootstrap",
      "url": ""
    },
    {
      "name": "Tailwind",
      "url": ""
    },
    {
      "name": "Materialize",
      "url": ""
    },
    {
      "name": "Quasar",
      "url": ""
    },
    {
      "name": "Git",
      "url": ""
    },
    {
      "name": "SQL",
      "url": ""
    }
  ],
  "showcases": [
    {
      "name": "IndoorCare",
      "description": "IndoorCare is a workplace wellness software solution that interprets complex indoor air quality data into important insights about an individual’s well-being. I have been assigned the task of developing the platform.",
      "role": "Full-stack Web Developer",
      "technologies": [
        {
          "name": "PHP"
        },
        {
          "name": "Laravel"
        },
        {
          "name": "JavaScript"
        },
        {
          "name": "Vue 3"
        },
        {
          "name": "Stripe"
        },
        {
          "name": "Soketi"
        },
        {
          "name": "Redis"
        },
        {
          "name": "MongoDB"
        },
        {
          "name": "Digital Ocean"
        },
        {
          "name": "Linux Servers"
        }
      ]
    },
    {
      "name": "Water Delivery Philippines",
      "description": "Water Delivery Philippines is an online platform and mobile application that facilitates the convenient ordering of top-notch drinking water from over 100+ reliable distributors located in the National Capital Region (NCR). I have been assigned the task of developing the 2.0 version of Water Delivery Philippines.",
      "role": "Full-stack Web/Mobile Developer",
      "technologies": [
        {
          "name": "PHP"
        },
        {
          "name": "Laravel"
        },
        {
          "name": "JavaScript"
        },
        {
          "name": "Vue 3"
        },
        {
          "name": "CapacitorJS"
        },
        {
          "name": "Ably"
        },
        {
          "name": "Digital Ocean"
        },
        {
          "name": "Linux Servers"
        }
      ]
    },
    {
      "name": "IMATCH",
      "description": "iMatch Realty Inc., a real estate company based in BGC, Manila and Boracay. My responsibility involves maintaining and introducing new features to the website",
      "role": "Full-stack Web Developer",
      "technologies": [
        {
          "name": "PHP"
        },
        {
          "name": "Laravel"
        },
        {
          "name": "JavaScript"
        },
        {
          "name": "Vue 2"
        },
        {
          "name": "Digital Ocean"
        },
        {
          "name": "Linux Servers"
        }
      ]
    },
    {
      "name": "Medgate",
      "description": "Medgate is a teleconsultation mobile app that allows patients to talk to doctors regarding various illnesses as well as receive follow-up care and virtual prescription. I was assigned to create and maintain the public website, web portal, and CSR chats part of the system.",
      "role": "Full-stack Web Developer",
      "technologies": [
        {
          "name": "PHP"
        },
        {
          "name": "Laravel"
        },
        {
          "name": "JavaScript"
        },
        {
          "name": "Vue 2"
        },
        {
          "name": "AWS"
        },
        {
          "name": "Linux Servers"
        }
      ]
    },
    {
      "name": "Inspire App",
      "description": "Inspire App is designed to publish content and have the church members watch or listen to these contents. I was assigned to create and maintain the web portal part of the system.",
      "role": "Full-stack Web Developer",
      "technologies": [
        {
          "name": "PHP"
        },
        {
          "name": "Laravel"
        },
        {
          "name": "JavaScript"
        },
        {
          "name": "Vue 2"
        },
        {
          "name": "AWS"
        },
        {
          "name": "Linux Servers"
        }
      ]
    },
    {
      "name": "ZWELL Philippines",
      "description": "ZWELL Philippine Realty Development Corp is a Philippine-based real-estate corporation. I was assigned to create and maintain ZWELLs web portal.",
      "role": "Full-stack Web Developer",
      "technologies": [
        {
          "name": "PHP"
        },
        {
          "name": "Laravel"
        },
        {
          "name": "JavaScript"
        },
        {
          "name": "Vue 2"
        },
        {
          "name": "AWS"
        },
        {
          "name": "Linux Servers"
        }
      ]
    }
  ]
}


###

### Get all portfolios
GET {{host}}/api/portfolios

###

### Get a portfolios by ID
GET {{host}}/api/portfolios/2
Authorization: Bearer {{ access_token }}

###

### Update a portfolios
PUT {{host}}/api/portfolios/1
Content-Type: application/json

{
  "name": "Updated Project",
  "description": "Updated description",
  "sub_domain": "updated-sub",
  "theme": "dark",
  "layout": "list",
  "type": "biz"
}

###

### Delete a portfolios
DELETE {{host}}/api/portfolios/3
Authorization: Bearer {{ access_token }}

###