CREATE TABLE IF NOT EXISTS `portfolios` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `project_id` BIGINT UNSIGNED NULL,
    `user_id` BIGINT UNSIGNED NULL,

    `name` VARCHAR(255) NOT NULL,
    `job_title` VARCHAR(255) NULL,
    `introduction` TEXT NULL,
    `about` TEXT NULL,
    `email` VARCHAR(255) NULL,
    `phone` VARCHAR(255) NULL,
    `website` VARCHAR(255) NULL,
    `github` VARCHAR(255) NULL,
    `linkedin` VARCHAR(255) NULL,
    `twitter` VARCHAR(255) NULL,

    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME NULL DEFAULT NULL,

    FOREIGN KEY (project_id) REFERENCES `projects`(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES `users`(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;