server {
    listen 2000;
    server_name api.kislap.app;

    set $cors_origin "https://builder.kislap.app";

    # ===== PRE-FLIGHT =====
    location / {
        if ($request_method = OPTIONS) {
            add_header 'Access-Control-Allow-Origin' $cors_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With, Accept, Origin' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Content-Length' 0;
            add_header 'Content-Type' 'text/plain; charset=UTF-8';
            return 204;
        }

        # ===== ACTUAL REQUESTS =====
        add_header 'Access-Control-Allow-Origin' $cors_origin always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;

        proxy_pass http://kislap_flash:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


server {
    listen 3000 default_server;
    server_name _;

    error_log  /var/log/nginx/admin-3000-error.log;
    access_log /var/log/nginx/admin-3000-access.log;

    location / {
        include fastcgi_params;
        fastcgi_pass kislap_admin:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        fastcgi_param PATH_INFO "";
    }
}

