@no-cookie-jar=false

### Base URL
@host = http://api.kislap.test
@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGtpc2xhcC5jb20iLCJleHAiOjE3NjIzOTgwNDIsInJvbGUiOiJkZWZhdWx0IiwidXNlcl9pZCI6Mn0.vXoHaQLE2A9PnbNo42i-BxiBxSAg8y9R9DmzaDqhUDs

###

### Create a new appointment
POST {{host}}/api/appointments
Content-Type: application/json

{
  "user_id": 1,
  "project_id": 1,
  "date": "2025-11-10T00:00:00Z",
  "time_from": "2025-11-10T10:00:00Z",
  "time_to": "2025-11-10T11:00:00Z"
}

###

### Get all appointments (requires authentication)
GET {{host}}/api/appointments/list
Authorization: {{access_token}}

###

### Get an appointment by ID
GET {{host}}/api/appointments/show/1
Authorization: {{access_token}}

###

### Update an appointment
PUT {{host}}/api/appointments/1
Content-Type: application/json
Authorization: {{access_token}}

{
  "date": "2025-11-12",
  "time_from": "14:00:00",
  "time_to": "15:00:00"
}

###

### Delete an appointment
DELETE {{host}}/api/appointments/1
Authorization: {{access_token}}
