@no-cookie-jar=false

### Base URL
@host = http://api.kislap.test
@access_token =
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlYmFzdGlhbmN1cnRpc2xhdmFyaWFzQGdtYWlsLmNvbSIsImV4cCI6MTc2NTEwNDIyMCwicm9sZSI6ImRlZmF1bHQiLCJ1c2VyX2lkIjoxfQ.Hbe-EFCTG2K6vsOJriTNYsp5eZ6IzmC3BSy6kHctYFc
###

### Track a generic Page View
POST {{host}}/api/page-activities
Content-Type: application/json

{
  "project_id": 1,
  "type": "view",
  "page_url": "/"
}

###

### Track a Click on a specific Model
POST {{host}}/api/page-activities
Content-Type: application/json

{
  "project_id": 1,
  "type": "click",
  "page_url": "/",
  "model_id": 1,
  "model_name": "Showcase"
}

###

### Get Dashboard Stats (Page 1)
GET {{host}}/api/page-activities/1?page=1&limit=10
Authorization: {{access_token}}

###

### Get Dashboard Stats (Page 2)
GET {{host}}/api/page-activities/1?page=2&limit=10
Authorization: {{access_token}}

###

### Get Top Pages (limit = 5)
GET {{host}}/api/page-activities/1/top-pages?limit=5
Authorization: {{access_token}}

###

### Get Top Pages (limit = 10)
GET {{host}}/api/page-activities/1/top-pages?limit=10
Authorization: {{access_token}}

###

### Get Recent Activities (Page 1, limit = 10)
GET {{host}}/api/page-activities/1/recent-activities?page=1&limit=10
Authorization: {{access_token}}

###

### Get Recent Activities (Page 3, limit = 25)
GET {{host}}/api/page-activities/1/recent-activities?page=3&limit=25
Authorization: {{access_token}}
